Feature/admin
saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE pull request #224
Opened 2024-10-20 05:21 UTC by samriddhitiwary

https://github.com/user-attachments/assets/ffca417e-1792-4f84-b73a-8d79731260e5

# Pull Request Template

**Title:** Create ADMIN page to CREATE, READ, UPDATE, and DELETE Products into MongoDB using existing CRUD API

## Description

Please provide a clear and concise description of what this pull request does, including any relevant details.

## Related Issue

Link to the issue that this pull request addresses (if applicable). Use the format: `Fixes #165 `

## Changes Made

This issue involves building an Admin page that allows for the Create, Read, Update, and Delete (CRUD) operations on Products stored in MongoDB. The page will interact with an existing CRUD API for product management. The page should include a form for product creation and editing, a table to display all products, and functionality to delete products.

## Checklist

- [x] I have tested my code and it works as expected.
- [x] I have added/updated documentation where necessary.
- [x] I have included tests for new features.
- [x] I have followed the project's coding standards.

- **Checklist:**
  - [x] I have tested my code and it works as expected.
  - [ ] I have added documentation for the changes made.
  - [x] I have included tests for the registration form validation.

2024-10-20 05:50 UTC, saurabhbakolia commented
Hey @samriddhitiwary , 
This is cool, I am reviewing it.

2024-10-20 06:06 UTC, samriddhitiwary commented
@thakuratul2 I have resolved the conflicts

2024-10-20 06:26 UTC, samriddhitiwary commented
@thakuratul2 I have resolved the conflict, could you please review the PR

2024-10-20 08:19 UTC, saurabhbakolia requested changes

2024-10-20 10:56 UTC, samriddhitiwary commented
@saurabhbakolia Ok I will check it again

2024-10-20 11:33 UTC, samriddhitiwary commented on backend/server.js
> -app.use("/api/auth", authStatusRoute); // Check Auth Status
@saurabhbakolia 
I am sorry, but, for time being, can hold all Auth related flow, Its causing lots of issue in local. We can have separate issue to fix all the auth related work. 

![image](https://github.com/user-attachments/assets/4e52d376-afa7-4ad2-a4da-567a686279de)

2024-10-20 11:34 UTC, samriddhitiwary commented on backend/api/routes/productRoute.js
> -router.post('/add', authMiddleware, productController.addProduct);
As of now, I have disabled all the auth flow. Later, we can add it in separate issue and PR?

2024-10-20 11:34 UTC, samriddhitiwary commented on src/components/UpdateProduct.jsx
> +      <div className='container mt-5'>
Sure, I am making these changes.

2024-10-20 11:36 UTC, samriddhitiwary commented on backend/server.js
> +// const PORT = process.env.PORT || 8080;
I am trying to connect the MongoDB ATLAS. It seems, existing code was not compatible with ATLAS, So when i modified, It started working. I did not try with local mongo db.

2024-10-20 11:36 UTC, samriddhitiwary commented on src/App.js
> +import Admin from './components/Admin';
Sure, I will do it. I missed it.

2024-10-20 11:36 UTC, samriddhitiwary commented on package.json
> +    "bootstrap": "^5.3.3",
I will check, I am not using anywhere. I will remove it.

2024-10-20 11:37 UTC, samriddhitiwary commented on package.json
> +    "react-hot-toast": "^2.4.1",
I will check and will use chakra-ui.

2024-10-20 11:37 UTC, samriddhitiwary commented on src/components/AddNewProduct.jsx
> +          minHeight: '100vh', // Ensure it covers the full height of the viewport
Sure, will do it.

2024-10-25 14:16 UTC, saurabhbakolia commented
> @saurabhbakolia Ok I will check it again

Hey @samriddhitiwary,

if you can make the required changes so that I can merge this PR.

2024-10-27 03:44 UTC, samriddhitiwary commented
@saurabhbakolia Yes yes

2024-10-27 03:47 UTC, samriddhitiwary commented
@saurabhbakolia I will create another fresh PR and I will close this PR

2024-10-27 06:49 UTC, closed without merging